### ISSUE TITLE
Can you please fix the CORS issue ?

### ISSUE THREAD

**Issue by yunan-adil** [bmai53/reddit-search#18]
Access to XMLHttpRequest at 'https://api.pushshift.io/reddit/search/submission?author=&title=&q=&subreddit=JennaFischer&size=50&after=&before=&sort=desc&sort_type=score' from origin 'https://bmai.dev' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Yesterday it worked well, but today isn't

**Comment by artemisreality** [comment]
Well, the problem is with the pushshift.io server. Everything works well now
